---
# See https://github.com/actions/virtual-environments
# https://github.com/marketplace/actions/setup-perl-environment

name: Test Code

# FIXME: IO::Compress::Brotli doesn't install on Windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '11 18 3 * *'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
#         - windows-latest
        perl: ['5.38', '5.36', '5.34', '5.32', '5.30', '5.28', '5.22']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iqn File::Spec ExtUtils::MakeMaker Test::Most
          cpanm -iqn Test::Script Test::Pod::Spelling::CommonMistakes Test::Portability::Files Test::Taint Test::Carp DBD::SQLite DBI CHI Test::Without::Module Locale::Language Test::Pod::Coverage
          cpanm -iq --installdeps --notest .
      - name: Install Windows Dependencies
        if: matrix.os == 'windows-latest'
        run: cpanm -iqn Win32::Process IPC::System::Simple
      - name: Install non Windows Dependencies
        if: matrix.os != 'windows-latest'
        run: cpanm -iqn IO::Compress::Brotli
      - name: Make Module
        run: |
          # find . -name build.log | xargs cat
          perl Makefile.PL
          make
      - name: Run Tests
        run: prove -l t
        env:
          AUTHOR_TESTING: 1
          AUTOMATED_TESTING: 1
